In [6]:
###importing the libraries
import numpy as np 
import pandas as pd 
from numpy import math 
  


from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt


In [7]:
dataset = pd.read_csv ("FuelConsumptionCo2 (new.csv")

In [8]:
dataset.head()

ENGINESIZE  CYLINDERS  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0         2.0          4                   9.9                  6.7   
1         2.4          4                  11.2                  7.7   
2         1.5          4                   6.0                  5.8   
3         3.5          6                  12.7                  9.1   
4         3.5          6                  12.1                  8.7   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244

In [9]:
ind_var = dataset.columns.tolist()


In [11]:
ind_var.remove('CO2EMISSIONS')

In [12]:
ind_var

['ENGINESIZE',
 'CYLINDERS',
 'FUELCONSUMPTION_CITY',
 'FUELCONSUMPTION_HWY',
 'FUELCONSUMPTION_COMB',
 'FUELCONSUMPTION_COMB_MPG']

In [16]:
X=dataset[ind_var].values
y=dataset['CO2EMISSIONS'].values

In [17]:
y


array([196, 221, 136, ..., 271, 260, 294], dtype=int64)

In [18]:
from sklearn.model_selection import train_test_split 
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42) 

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
X_train

array([[0.13513514, 0.11111111, 0.36470588, 0.34615385, 0.35714286,
        0.25      ],
       [0.35135135, 0.33333333, 0.32941176, 0.24358974, 0.3       ,
        0.29166667],
       [0.59459459, 0.55555556, 0.62352941, 0.67948718, 0.64285714,
        0.08333333],
       ...,
       [0.45945946, 0.55555556, 0.45098039, 0.38461538, 0.42857143,
        0.1875    ],
       [0.10810811, 0.11111111, 0.20784314, 0.12820513, 0.18095238,
        0.45833333],
       [0.62162162, 0.55555556, 0.58823529, 0.6025641 , 0.5952381 ,
        0.10416667]])

In [20]:
X_train.shape

(746, 6)

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train , y_train)

LinearRegression()

In [22]:
y_pred=regressor.predict(X_test)

In [24]:
y_pred.shape

(321,)

In [25]:
accuracay = r2_score(y_test , y_pred)

In [26]:
accuracay

0.9032576748788013

In [32]:
regressor.predict(inverse_transform([[0.13513514, 0.11111111, 0.36470588, 0.34615385, 0.35714286,
        0.25      ]]))

NameError: name 'inverse_transform' is not defined

In [38]:
y_Pred=regressor.predict([[2 , 4 , 9.9 , 6.7  , 8.5, 33]])

In [40]:
y_Pred

array([-5460.45973492])