In [138]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt


In [139]:
dataset = pd.read_csv("oooo.csv")


In [140]:
dataset.head()

Age  Mobile Phone  Purchased
0   15          6334          0
1   28          6667          0
2   20         14334          0
3   21         19000          0
4   15         25334          0

In [141]:
X = dataset.iloc[0:199 , 0:2].values
y = dataset.iloc[0:199 , -1].values

y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0], dtype=int64)

In [142]:
#splitting the data
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y  , test_size=0.2 , random_state=42)

In [143]:
print(X_test)

[[   39 24667]
 [   21 18000]
 [   31 14000]
 [   43 34667]
 [   27 14334]
 [   39 29667]
 [   16 27334]
 [   19  7667]
 [   44 34667]
 [   30 16667]
 [   31 25000]
 [   30 23667]
 [   28 15667]
 [   18 22000]
 [   37 15667]
 [   46 33667]
 [   17 18334]
 [   27 38334]
 [   36  7334]
 [   38 46000]
 [   24 45000]
 [   32 17334]
 [   39 21667]
 [   37 37667]
 [   20  7334]
 [   38 39667]
 [   45 24667]
 [   28 21667]
 [   19 10667]
 [   38 44667]
 [   33 21667]
 [   15  7000]
 [   45 20000]
 [   44 13000]
 [   28 30334]
 [   26 13667]
 [   35 13000]
 [   45 40667]
 [   22 29667]
 [   16 12000]]


In [144]:
#feature scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test  = sc.transform(X_test)


In [145]:
#Logistic Regreesion model 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=42)
classifier.fit(X_train , y_train )

LogisticRegression(random_state=42)

In [147]:
#predciting the results
y_pred = classifier.predict(sc.transform([[54 , 41000]]))
print(y_pred)


[1]


In [148]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]]


In [149]:
#confusion Matrix
from sklearn.metrics import confusion_matrix ,  accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
accuracy_score(y_test , y_pred)

[[23  2]
 [ 3 12]]


0.875