In [105]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np



In [106]:
dataset =pd.read_csv("Bank Customer Churn Prediction.csv")
dataset.head()

customer_id  credit_score country  gender  age  tenure    balance  \
0     15634602           619  France  Female   42       2       0.00   
1     15647311           608   Spain  Female   41       1   83807.86   
2     15619304           502  France  Female   42       8  159660.80   
3     15701354           699  France  Female   39       1       0.00   
4     15737888           850   Spain  Female   43       2  125510.82   

   products_number  credit_card  active_member  estimated_salary  churn  
0                1            1              1         101348.88      1  
1                1            0              1         112542.58      0  
2                3            1              0         113931.57      1  
3                2            0              0          93826.63      0  
4                1            1              1          79084.10      0

In [107]:
#data Preprocessing 
dataset=dataset[["credit_score" , 'age' , 'tenure' , 'balance' , 'estimated_salary' , 'churn' ]]
dataset['churn']=dataset['churn'].astype('int')
dataset.head()

credit_score  age  tenure    balance  estimated_salary  churn
0           619   42       2       0.00         101348.88      1
1           608   41       1   83807.86         112542.58      0
2           502   42       8  159660.80         113931.57      1
3           699   39       1       0.00          93826.63      0
4           850   43       2  125510.82          79084.10      0

In [108]:

#normalize the data 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X=sc.fit_transform(X)
X

array([[-0.32622142,  0.29351742, -1.04175968, -1.22584767,  0.02188649],
       [-0.44003595,  0.19816383, -1.38753759,  0.11735002,  0.21653375],
       [-1.53679418,  0.29351742,  1.03290776,  1.33305335,  0.2406869 ],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, -1.22584767, -1.00864308],
       [ 1.25683526,  0.29351742, -0.69598177, -0.02260751, -0.12523071],
       [ 1.46377078, -1.04143285, -0.35020386,  0.85996499, -1.07636976]])

In [109]:
X = dataset.iloc[: , :-1]
y = dataset.iloc[: , -1]
X

credit_score  age  tenure    balance  estimated_salary
0              619   42       2       0.00         101348.88
1              608   41       1   83807.86         112542.58
2              502   42       8  159660.80         113931.57
3              699   39       1       0.00          93826.63
4              850   43       2  125510.82          79084.10
...            ...  ...     ...        ...               ...
9995           771   39       5       0.00          96270.64
9996           516   35      10   57369.61         101699.77
9997           709   36       7       0.00          42085.58
9998           772   42       3   75075.31          92888.52
9999           792   28       4  130142.79          38190.78

[10000 rows x 5 columns]

In [132]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)
print(X_train.shape)
print(y_test)

(8000, 5)
6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: churn, Length: 2000, dtype: int32


In [133]:
#model selction Logistic regression
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state=42)
classifier.fit(X_train , y_train)

LogisticRegression(random_state=42)

In [134]:
y_Pred = classifier.predict(X_test)
print(y_Pred)

[0 0 0 ... 0 0 0]


In [135]:
from sklearn.metrics import confusion_matrix ,accuracy_score 
cf = confusion_matrix(y_test , y_Pred)
cf 

array([[1573,   34],
       [ 365,   28]], dtype=int64)

In [136]:
accuracy_score(y_test , y_pred)

0.8005