In [37]:
#iporting the libarries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [38]:
dataset=pd.read_csv('accenture salary.csv')
X = dataset.iloc[0:12 , 1:-1].values
y = dataset.iloc[0:12 , -1].values

In [39]:
print(X)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [12.]
 [13.]]


In [40]:
print(y)

[  17000.   27000.   40000.   65000.  100000.  150000.  250000.  400000.
  650000. 1000000. 1800000. 4000000.]


Feature Scaling

In [41]:
y = y.reshape(len(y), 1)
print(y)

[[  17000.]
 [  27000.]
 [  40000.]
 [  65000.]
 [ 100000.]
 [ 150000.]
 [ 250000.]
 [ 400000.]
 [ 650000.]
 [1000000.]
 [1800000.]
 [4000000.]]


Training the sSVR model ont he whole dataset

In [42]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [43]:
print (X) , print(y)

[[-1.52973232]
 [-1.25977956]
 [-0.9898268 ]
 [-0.71987403]
 [-0.44992127]
 [-0.17996851]
 [ 0.08998425]
 [ 0.35993702]
 [ 0.62988978]
 [ 0.89984254]
 [ 1.43974807]
 [ 1.70970083]]
[[-0.62024154]
 [-0.61126879]
 [-0.59960421]
 [-0.57717233]
 [-0.54576769]
 [-0.50090393]
 [-0.4111764 ]
 [-0.27658511]
 [-0.05226629]
 [ 0.26178007]
 [ 0.9796003 ]
 [ 2.95360593]]


(None, None)

Making the SVR model

In [44]:
from sklearn.svm import SVR 
regressor = SVR(kernel = 'rbf')
regressor.fit(X ,y)

c:\users\yash\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Predicting a new results 

In [46]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])))

ValueError: Expected 2D array, got 1D array instead:
array=[-0.36788056].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.